version: "3"
services:
  tweetycs_bak:
    image: banian/node
    volumes:
      - "./:/usr/src/app"
    depends_on:
      - tweetycs_db
    network_mode: 'bridge'
    restart: always

  tweetycs_db:
    image: mongo
    volumes:
      - "./database/:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=MONGO_PASS
    network_mode: "bridge"
    restart: always
