version: '3.1'

services:

  bak:
    image: bak
    restart: always
    environment:
      MONGO_USERNAME: secret
      MONGO_PASSWORD: secret
      MONGO_HOSTNAME: mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: secret
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - "./data/:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: secret
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_BASICAUTH_USERNAME: secret
      ME_CONFIG_BASICAUTH_PASSWORD: secret
      ME_CONFIG_MONGODB_ADMINUSERNAME: secret
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
